stackabletech/secret-operator

.readme/partials/main.md.j2
README.md

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

docs: Secret Operator installation guide link updated

---

Cargo.lock
Cargo.toml
rust/krb5-provision-keytab/Cargo.toml
rust/krb5-sys/Cargo.toml
rust/krb5/Cargo.toml
rust/krb5/src/lib.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/csi_server/node.rs

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Switch to workspace dependencies

---

docs/modules/secret-operator/pages/openshift.adoc
docs/modules/secret-operator/pages/troubleshooting.adoc

Fixes https://github.com/stackabletech/issues/issues/419

Add installation notes for OpenShift

---

Cargo.lock
Cargo.toml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Bump operator-rs to 0.56.1

---

deploy/helm/secret-operator/values.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add Stackable vendor label to default values.yaml

---

tests/release.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(test): add listener test dependency

---

tests/release.yaml
tests/templates/kuttl/kerberos-ad/00-patch-ns.yaml.j2
tests/templates/kuttl/kerberos/00-patch-ns.yaml.j2
tests/templates/kuttl/listener/00-patch-ns.yaml.j2
tests/templates/kuttl/tls/00-patch-ns.yaml.j2

Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (80.51s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/tls_openshift-true (29.47s)
--- PASS: kuttl/harness/kerberos_openshift-true (37.95s)
--- PASS: kuttl/harness/listener_openshift-true (43.01s)
```
Azure:
```
--- PASS: kuttl (90.92s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/tls_openshift-false (19.15s)
--- PASS: kuttl/harness/listener_openshift-false (22.69s)
--- PASS: kuttl/harness/kerberos_openshift-false (70.02s)
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

tests: added namespace patch for openshift tests

---

CHANGELOG.md
deploy/helm/secret-operator/crds/crds.yaml
rust/operator-binary/src/backend/tls/mod.rs

Part of #358 
```[tasklist]
```
```[tasklist]
```

chore: Reduce CA default lifetime to 1 year

---

CHANGELOG.md
deploy/helm/secret-operator/values.yaml

Upgrade the CSI images in the Helm values
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade the CSI images in the Helm values

---

docs/modules/secret-operator/pages/usage.adoc

Part of #358.
Add note about current default CA lifetime, and it being lowered over time
```[tasklist]
```
```[tasklist]
```

docs: Add note about current default CA lifetime

---

Makefile

testing gh action behaviour
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Revert Update Makefile

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

Part of https://github.com/stackabletech/issues/issues/601, https://github.com/stackabletech/issues/issues/557
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: bump cargo dependencies

---

deploy/helm/secret-operator/templates/roles.yaml

See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): use the same scc as olm

---

deploy/helm/secret-operator/templates/roles.yaml

```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): scc indentation

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/backend/pod_info.rs

Part of https://github.com/stackabletech/issues/issues/640
This should also help getting https://github.com/stackabletech/secret-operator/pull/494 over the finish line
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update to operator-rs 0.76.0

---

Cargo.lock
docs/modules/secret-operator/pages/secretclass.adoc

Small cleanup of https://github.com/stackabletech/secret-operator/pull/506
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix TLS key length admonition

---

docs/modules/secret-operator/pages/scope.adoc

Fixes #496 (hopefully).
Also moves the listener volume scope to the top of the list and adds caveats to the other scopes.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Rewrite listener volume docs

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

Needed to fix kafka and hdfs integration tests
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Bump to stackable-operator 0.81.0

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/secret-operator/Chart.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```

chore: Update to operator-rs 0.84.0

---

deploy/helm/secret-operator/values.yaml
nix/sources.json
tests/templates/kuttl/kerberos/kinit-client.yaml.j2

Part of https://github.com/stackabletech/docker-images/issues/975, https://github.com/stackabletech/docker-images/issues/976
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade CSI sidecars

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
tests/templates/kuttl/kerberos/kinit-client.yaml.j2

This reverts the FQDNization-by-default from 0.84.0
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade to op-rs 0.84.1

---

docs/modules/secret-operator/pages/scope.adoc

Docs: fix listener volume link

---

rust/operator-binary/src/backend/tls/mod.rs

Due to the nature of temporal paradoxes, we can't be certain about which case is actually true in the current timeline.

Clarify temporal uncertainty regarding time machines

---

CHANGELOG.md
deploy/helm/secret-operator/values.yaml

Part of https://github.com/stackabletech/docker-images/issues/1232
```
-- PASS: kuttl (193.62s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/tls-truststore_openshift-false_truststore-target-kind-ConfigMap (6.68s)
--- PASS: kuttl/harness/kerberos_krb5-1.21.1_openshift-false (87.59s)
--- PASS: kuttl/harness/cert-manager-tls_openshift-false (99.40s)
--- PASS: kuttl/harness/tls-truststore_openshift-false_truststore-target-kind-Secret (7.88s)
--- PASS: kuttl/harness/listener_openshift-false (28.31s)
--- PASS: kuttl/harness/tls_openshift-false_rsa-key-length-3072_custom-secret-names-True (51.44s)
--- PASS: kuttl/harness/tls_openshift-false_rsa-key-length-3072_custom-secret-names-False (66.71s)
--- PASS: kuttl/harness/tls_openshift-false_rsa-key-length-2048_custom-secret-names-True …
```

chore: Bump csi-provisioner version for 25.11.0
