stackabletech/secret-operator

Cargo.lock
Cargo.toml
src/main.rs
src/utils.rs

Fixes #16
This is a bit more complicated than it ought to be, because neither Tokio nor std expose a proper API for this (see https://github.com/tokio-rs/tokio/issues/4422).

Lock down file permissions on CSI socket

---

rust/operator-binary/src/format/convert.rs

https://github.com/stackabletech/secret-operator/pull/314 only sets the password for the PKCS#12 keystore.
This PR sets the same password (taken from `secrets.stackable.tech/format.compatibility.tls-pkcs12.password`) for the truststore. NiFi for example requires a non-blank password for the provided PKCS#12 truststore: https://github.com/apache/nifi/blob/00dc79c633d3ef4a2e49a70d4fe6190f1cd61a2d/nifi-commons/nifi-security-utils/src/main/java/org/apache/nifi/security/util/KeyStoreUtils.java#L365-L367
The bmp_string function was copied from here: https://github.com/hjiayz/p12/blob/0b3b2e1a141c7c2384e85f3737dcc4d4ab4e8b9c/src/lib.rs#L723
- Please make sure …

Set same password for truststore as for keystore

---

tests/templates/kuttl/listener/01-install-nginx.yaml

Use correct listener class in integration tests.
The default listener class `nodeport` was replaced with `external-stable`/`external-unstable` in stackabletech/listener-operator#117.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Use correct listener class in integration tests

---

docs/modules/secret-operator/pages/secretclass.adoc

As requested by @lfrancke (https://github.com/stackabletech/secret-operator/issues/93#issuecomment-1921381739)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

CA rotation docs cleanups

---

CHANGELOG.md
Cargo.lock
docs/modules/secret-operator/pages/secretclass.adoc
docs/modules/secret-operator/pages/volume.adoc
rust/operator-binary/Cargo.toml
rust/operator-binary/src/backend/mod.rs
rust/operator-binary/src/backend/tls/mod.rs
tests/templates/kuttl/tls/consumer.yaml

Fixes #159.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Jitter certificate lifetimes

---

CHANGELOG.md
deploy/helm/secret-operator/crds/crds.yaml
docs/modules/secret-operator/pages/secretclass.adoc
rust/operator-binary/src/backend/tls/mod.rs
rust/operator-binary/src/crd.rs

https://github.com/stackabletech/issues/issues/514 showed that we end up generating keystores that not all products currently support.
As a workaround we're putting rotation behind a feature flag until that has been resolved.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Disable CA rotation by default for now

---

docs/modules/secret-operator/pages/secretclass.adoc

This fixes the break introduced in PR #361. It is caused by invalid numbering in an ordered list. See https://github.com/stackabletech/documentation/runs/21358715623.

chore(docs): Remove explicit numbering from list

---

CHANGELOG.md
deploy/helm/secret-operator/crds/crds.yaml
docs/modules/secret-operator/pages/secretclass.adoc
rust/operator-binary/src/backend/tls/mod.rs
rust/operator-binary/src/crd.rs

Reverts stackabletech/secret-operator#363
This turned out not to be the culprit after all, so let's turn it back on.

Revert "Disable CA rotation by default for now"

---

.readme/partials/main.md.j2
BUILDING.md
README.md
docs/modules/secret-operator/pages/installation.adoc
docs/modules/secret-operator/partials/nav.adoc

docs: move build instructions from Antora into Markdown

---

docs/modules/secret-operator/examples/volume-pod.yaml

The docs say:
> 2. This secret should be scoped by the intersection of node, pod, and the service named secret-consumer
But the example yaml only showed the `node` scope.

docs: update example to match description on the page

---

CHANGELOG.md
deploy/helm/secret-operator/templates/secretclasses.yaml
deploy/helm/secret-operator/values.yaml

See https://github.com/stackabletech/issues/issues/498. OLM manifests are generated from the Helm charts, so fixing it in one should fix it in the other.
Note that this is a breaking change, existing users will need to either `--set secretClasses.tls.caSecretNamespace=default` or copy their CA secret across (`kubectl -n default get secret/secret-provisioner-tls-ca -o json | jq '.metadata.namespace = "stackable-operators"' | kubectl create -f-`).
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Default to installing the TLS CA into the operator's target namespace

---

docs/modules/secret-operator/pages/secretclass.adoc
docs/modules/secret-operator/pages/troubleshooting.adoc
rust/krb5-provision-keytab/src/active_directory.rs

Fixes #406.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Document AD principal conflicts

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/krb5-provision-keytab/src/active_directory.rs
rust/krb5-provision-keytab/src/credential_cache.rs
rust/krb5-sys/build.rs
rust/operator-binary/build.rs
rust/operator-binary/src/backend/dynamic.rs
rust/operator-binary/src/backend/k8s_search.rs
rust/operator-binary/src/backend/kerberos_keytab.rs
rust/operator-binary/src/backend/pod_info.rs
rust/operator-binary/src/csi_server/controller.rs
rust/operator-binary/src/csi_server/node.rs
rust/operator-binary/src/main.rs

- Bump operator-rs, and external crates
- Fix broken code
- regenerate-nix
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Bump dependencies

---

rust/krb5-sys/build.rs

`arm64` builds have been broken for `secret-operator` since the va_list type was not FFI safe.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Patch for borken arm64 builds

---

deploy/helm/secret-operator/templates/secret_migration_job.yaml

This fixes testing of PR versions of secret-operator since the testruns got broken by https://github.com/stackabletech/secret-operator/pull/476
We stumbed across this:
> When I run a custom test with secret-operator I’m allowed to choose a PR-Version like secret=0.0.0-pr455 which then in the secret-migration Job causes the image being docker.stackable.tech/stackable/tools:1.0.0-stackable0.0.0-pr455 which is a consequence of the image selection mechanism.
Since the `tools` image does not have PR artifacts that relate to the PRs in secret-operator we now specify a fixed version so that testing PRs works again. Currently it fails because the according `tools` image is not present.
We're using 24.7.0 because it's multiarch. It's manually built for now to make this work and will get rebuilt by …

Fix: Always use the 24.7.0 version of the tools image because testing PR artifacts breaks otherwise

---

CHANGELOG.md
rust/krb5-provision-keytab/src/lib.rs

`KRB5CCNAME=MEMORY` will store the cache in a file named `MEMORY`, `KRB5CCNAME=MEMORY:` will store the cache in memory (as intended).
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Actually disable credential cache for krb5 provisioner

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/src/main.rs

Part of https://github.com/stackabletech/issues/issues/636
Tested using k8s 1.26 (`kind create cluster --image kindest/node:v1.26.15`)
```
--- PASS: kuttl (55.76s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/tls_openshift-false (29.43s)
--- PASS: kuttl/harness/kerberos_krb5-1.21.1_openshift-false (52.96s)
--- PASS: kuttl/harness/listener_openshift-false (26.32s)
PASS
```
On k8s `1.25.16` it fails with `"Registration process failed with error, restarting registration container" err="RegisterPlugin error -- plugin registration failed with err: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"`, so I'd call it fixed :+1: 
- Not all of these items are applicable to all PRs, the author should update this template to only leave the …

chore: Remove h2 patch

---

CHANGELOG.md
deploy/helm/secret-operator/templates/roles.yaml

This is required for listener volume scopes that use manually created listeners
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Give RBAC permission to read listeners

---

docs/modules/secret-operator/pages/reference/environment-variables.adoc
docs/modules/secret-operator/pages/reference/index.adoc

Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs.
part of https://github.com/stackabletech/issues/issues/668

Adds missing KUBERNETES_CLUSTER_DOMAIN environment variable to docs

---

CHANGELOG.md
deploy/helm/secret-operator/templates/secret_migration_job.yaml
deploy/helm/secret-operator/templates/secret_migration_rbac.yaml
deploy/helm/secret-operator/values.yaml

* Helm chart: The secret migration job can be omitted via Helm values.
* Helm chart: The tag of the tools image used for the secret migration job can be changed in the Helm values and defaults to the current SDP version instead of 24.7.0.
part of #477 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix(helm): Add configuration options for the secret migration job

---

docs/modules/secret-operator/pages/secretclass.adoc

Documentation mirror of https://github.com/stackabletech/ad-init/pull/2.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Document required AD ACLs

---

CHANGELOG.md
rust/operator-binary/src/backend/kerberos_keytab.rs
tests/templates/kuttl/kerberos/01-install-kdc.yaml.j2
tests/templates/kuttl/kerberos/kinit-client.yaml.j2
tests/templates/kuttl/kerberos/listenerclass.yaml

Previously, Kerberos principals were only provisioned for hostnames. This PR also adds support for IP addresses, since we default to using IP addresses for NodePort listeners (vs the old `node` scope, which used hostnames).
Fixes https://github.com/stackabletech/kafka-operator/issues/812.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Provision Kerberos principals for IP addresses

---

CHANGELOG.md
rust/operator-binary/src/crd.rs

Fixes #562
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Allow underscores in kerberos principal names

---

docs/modules/secret-operator/pages/secretclass.adoc

Fix the k8sSearch example.
The Pod specification was invalid and the label `secrets.stackable.tech/pod` on the Secret was missing.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Fix the k8sSearch example

---

Cargo.lock
Cargo.nix
deny.toml
docs/modules/secret-operator/pages/installation.adoc

Fixes #574
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add note about Tanzu kubeletDir

---

docs/modules/secret-operator/pages/troubleshooting.adoc

Part of the effort of making it easier to find for customers (according to feedback of them)
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Hint on kubelet dir special installation guides

---

CHANGELOG.md
deploy/helm/secret-operator/crds/crds.yaml
deploy/helm/secret-operator/templates/roles.yaml
docs/modules/secret-operator/pages/secretclass.adoc
rust/crd-utils/src/lib.rs
rust/operator-binary/src/backend/dynamic.rs
rust/operator-binary/src/backend/tls/ca.rs
rust/operator-binary/src/backend/tls/mod.rs
rust/operator-binary/src/crd.rs
tests/templates/kuttl/tls/02-rbac.yaml.j2
tests/templates/kuttl/tls/03-create-trust-roots.yaml
tests/templates/kuttl/tls/consumer.yaml
tests/templates/kuttl/tls/secretclass.yaml.j2

Allow the specification of additional trust roots in autoTls SecretClasses
Closes #570 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Allow the specification of additional trust roots

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/secret-operator/Chart.yaml
deploy/helm/secret-operator/crds/crds.yaml
docs/antora.yml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.3.0

---

docs/modules/secret-operator/pages/secretclass.adoc

Document the SecretClass property `additionalTrustRoots.configMap`
This change will also be added to the release branch of 25.3.0.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Document the SecretClass property additionalTrustRoots.configMap

---

CHANGELOG.md
docs/modules/secret-operator/pages/volume.adoc
rust/operator-binary/src/backend/mod.rs
rust/operator-binary/src/csi_server/node.rs
rust/operator-binary/src/format/convert.rs
rust/operator-binary/src/format/mod.rs
rust/operator-binary/src/format/well_known.rs
tests/templates/kuttl/tls/consumer.yaml.j2
tests/test-definition.yaml

This PR adds support to customize the secret file names using `secrets.stackable.tech` annotations on the volume. The following attributes were added:
- `secrets.stackable.tech/format.tls-pkcs12.keystore-name`
- `secrets.stackable.tech/format.tls-pkcs12.truststore-name`
- `secrets.stackable.tech/format.tls-pem.cert-name`
- `secrets.stackable.tech/format.tls-pem.key-name`
- `secrets.stackable.tech/format.tls-pem.ca-name`
This came up in demo testing during the 25.3.0 SPD release, see https://github.com/stackabletech/demos/issues/157#issuecomment-2729108153.
This PR adds a new test dimension which is used in the `tls` tests. All adjusted tests pass:
```
--- PASS: kuttl (98.75s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/tls_openshift-false_rsa-key-length-3072_custom-secret-names …
```

feat: Add format-specific annotations to override secret file names

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/olm-deployer/Cargo.toml
rust/olm-deployer/src/main.rs
rust/operator-binary/Cargo.toml
rust/operator-binary/src/main.rs

**Use `Tracing::pre_configured` from stackable-telemetry**
Breaking changes:
- The console log level was set by `SECRET_PROVISIONER_LOG`, and is now set by `CONSOLE_LOG`.
- The file log level was set by `SECRET_PROVISIONER_LOG`, and is now set by `FILE_LOG`.
- The file log directory was previously changed to `ROLLING_LOGS`, but has been updated to `ROLLING_LOGS_DIR`.
Breaking changes:
- The console log level was set by `STKBL_SECRET_OLM_DEPLOYER_LOG`, and is now set by `CONSOLE_LOG`.
- The file log level was set by `STKBL_SECRET_OLM_DEPLOYER_LOG`, and is now set by `FILE_LOG`.
- The file log directory was previously changed to `ROLLING_LOGS`, but has been updated to `ROLLING_LOGS_DIR`.
- Not all of these items are applicable to all PRs, the author should update this template to only leave …

feat!: Use `Tracing::pre_configured` from stackable-telemetry

---

CHANGELOG.md
deploy/helm/secret-operator/values.yaml

Part of https://github.com/stackabletech/docker-images/issues/1064
Note: Image mirrored by https://github.com/stackabletech/docker-images/actions/runs/14833003316
> [!TIP]
> Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
Please make sure all these things are done and tick the boxes

chore: Bump csi-provisioner to 5.2.0

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/secret-operator/templates/daemonset.yaml
deploy/helm/secret-operator/templates/roles.yaml
docs/modules/secret-operator/pages/troubleshooting.adoc
rust/operator-binary/src/backend/cert_manager.rs
rust/operator-binary/src/backend/dynamic.rs
rust/operator-binary/src/backend/tls/ca.rs
rust/operator-binary/src/grpc.rs
rust/operator-binary/src/main.rs
tests/templates/kuttl/kerberos-ad/kinit-client.yaml.j2
tests/templates/kuttl/kerberos/kinit-client.yaml.j2

Part of <https://github.com/stackabletech/issues/issues/725>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.

chore: Bump Rust dependencies pre-25.7.0

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/krb5-provision-keytab/src/lib.rs
rust/krb5-provision-keytab/src/main.rs
rust/operator-binary/src/main.rs

Fixup of https://github.com/stackabletech/secret-operator/pull/602.
That PR added a check and uncovered a bug in krb5-provision-keytab returning a wrong exit code.
As I originally though the bug was related to CLI arguments, I bumped op-rs. Doesn't really belong here, but also doesn't hurt.

fix: Return correct exit code in krb5-provision-keytab

---

CHANGELOG.md
deploy/helm/secret-operator/templates/daemonset.yaml
deploy/helm/secret-operator/values.yaml

Part of stackabletech/issues#763
> [!NOTE]
> These changes aren't exactly consistent with listener-operator changes from https://github.com/stackabletech/listener-operator/pull/334, but are a step towards consistency, and make it easier should we decide to split secret-operator into a CSI Provisioner Deployment and CSI Node Driver DaemonSet.
> [!CAUTION]
> The original values are no longer valid.
- `image.repository` has been moved to `secretOperator.image.repository`.
- `image.tag` has been moved to `secretOperator.image.tag`.
- `image.pullPolicy` has been moved to `secretOperator.image.pullPolicy`.
- `csiProvisioner` values have been moved to `externalProvisioner`.
- `csiNodeDriverRegistrar` values have been moved to `nodeDriverRegistrar`.
- `node.driver` values have been moved to …

chore(helm)!: Rearrange values to be somewhat consistent with the listener-operator value changes
